_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 71
            "2":
                - 1
                - 11
                - 49
                - 55
                - 71
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.15
            "5": 0.18.7
            "6": 4.46.3
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
add_lora:
    value: false
always_save_checkpoint:
    value: false
backend:
    value: nccl
batch_size:
    value: 1
beta1:
    value: 0.9
beta2:
    value: 0.95
bias:
    value: false
block_size:
    value: 1024
compile:
    value: true
dataset:
    value: tinystories
decay_lr:
    value: false
device:
    value: cuda
dropout:
    value: 0
dtype:
    value: bfloat16
eval_interval:
    value: 5
eval_iters:
    value: 40
eval_only:
    value: false
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 32
init_from:
    value: gpt2
is_moe:
    value: true
learning_rate:
    value: 0.03
log_interval:
    value: 1
lr_decay_iters:
    value: 600000
max_iters:
    value: 100
min_lr:
    value: 6e-05
n_embd:
    value: 768
n_head:
    value: 12
n_layer:
    value: 12
out_dir:
    value: out-tinystories
wandb_log:
    value: true
wandb_project:
    value: ngpt-tinystories
wandb_run_name:
    value: ft-baselines-1740806007.837674
warmup_iters:
    value: 2000
weight_decay:
    value: 0.1
